### ISSUE TITLE
the result of if() compare condition is wrong

### ISSUE THREAD

**Issue by klom303** [microsoft/etcd3#104]
etcd3 Version: 0.2.13
etcd Version: 3.3.12
nodejs Version: 10.15.3
OS: Ubuntu 18.04

In a transaction, `if()` support compare condition.
In my case, I want to compare `Value` to a number, but the result is wrong.

```js
const Etcd3 = require('etcd3').Etcd3;

const client = new Etcd3({hosts: ['192.168.142.135:2379']});

(async () => {
  const key = 'test_key';
  const oldValue = 9;
  const newValue = 10;
  await client.put(key).value(oldValue).exec();
  const response = await client.if(key, 'Value', '<', newValue).then(client.put(key).value(newValue)).commit();
  console.log(response);
})();
```

response 
```js
{ responses: [],
  header:
   { cluster_id: '18011104697467366872',
     member_id: '6460912315094810421',
     revision: '583',
     raft_term: '7' },
  succeeded: false }
```
It seems before the compare step, the number parameter was converted to a string.
Is this the correct usage ?

**Comment by connor4312** [comment]
How is your number being stored? Comparing the value uses the [byte sort order](https://github.com/etcd-io/etcd/blob/9c5426830b1b8728af14e069acfdc2a64dea768c/etcdserver/apply.go#L468-L473). So "1" is less than "700", since the byte for the character 1 comes before 7.

If this is the problem, I'd suggest storing your numbers encoded as big endian integers to make sure the sort is correct.
